const ERROR_CODES = Object.freeze({
    INTERNAL_ERROR: "INTERNAL_ERROR",
    NOT_FOUND: "NOT_FOUND",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    RATE_LIMITED: "RATE_LIMITED",
    DATABASE_ERROR: "DATABASE_ERROR",
    CONFIGURATION_ERROR: "CONFIGURATION_ERROR",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    INVALID_TOKEN: "INVALID_TOKEN",
    EXPIRED_TOKEN: "EXPIRED_TOKEN",
    REVOKED_TOKEN: "REVOKED_TOKEN",
    OWNERSHIP_REQUIRED: "OWNERSHIP_REQUIRED",
    DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE"
});

module.exports = {
    ERROR_CODES
};
